// Autogenerated from Pigeon (v9.0.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#import <Foundation/Foundation.h>

@protocol FlutterBinaryMessenger;
@protocol FlutterMessageCodec;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN

@class FLTSearchRequest;
@class FLTSearchReply;

@interface FLTSearchRequest : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithQuery:(NSString *)query;
@property(nonatomic, copy) NSString * query;
@end

@interface FLTSearchReply : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithResult:(NSString *)result;
@property(nonatomic, copy) NSString * result;
@end

/// The codec used by FLTFlutterCallNativeApi.
NSObject<FlutterMessageCodec> *FLTFlutterCallNativeApiGetCodec(void);

/// flutter call native
@protocol FLTFlutterCallNativeApi
/// @return `nil` only when `error != nil`.
- (nullable FLTSearchReply *)searchRequest:(FLTSearchRequest *)request error:(FlutterError *_Nullable *_Nonnull)error;
@end

extern void FLTFlutterCallNativeApiSetup(id<FlutterBinaryMessenger> binaryMessenger, NSObject<FLTFlutterCallNativeApi> *_Nullable api);

/// The codec used by FLTNativeCallFlutterApi.
NSObject<FlutterMessageCodec> *FLTNativeCallFlutterApiGetCodec(void);

/// native call flutter
@interface FLTNativeCallFlutterApi : NSObject
- (instancetype)initWithBinaryMessenger:(id<FlutterBinaryMessenger>)binaryMessenger;
- (void)queryRequest:(FLTSearchRequest *)request completion:(void (^)(FLTSearchReply *_Nullable, FlutterError *_Nullable))completion;
@end

NS_ASSUME_NONNULL_END
