// Autogenerated from Pigeon (v9.0.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#import "Pigeon.h"
#import <Flutter/Flutter.h>

#if !__has_feature(objc_arc)
#error File requires ARC to be enabled.
#endif

static NSArray *wrapResult(id result, FlutterError *error) {
  if (error) {
    return @[
      error.code ?: [NSNull null], error.message ?: [NSNull null], error.details ?: [NSNull null]
    ];
  }
  return @[ result ?: [NSNull null] ];
}
static id GetNullableObjectAtIndex(NSArray *array, NSInteger key) {
  id result = array[key];
  return (result == [NSNull null]) ? nil : result;
}

@interface FLTSearchRequest ()
+ (FLTSearchRequest *)fromList:(NSArray *)list;
+ (nullable FLTSearchRequest *)nullableFromList:(NSArray *)list;
- (NSArray *)toList;
@end

@interface FLTSearchReply ()
+ (FLTSearchReply *)fromList:(NSArray *)list;
+ (nullable FLTSearchReply *)nullableFromList:(NSArray *)list;
- (NSArray *)toList;
@end

@implementation FLTSearchRequest
+ (instancetype)makeWithQuery:(NSString *)query {
  FLTSearchRequest* pigeonResult = [[FLTSearchRequest alloc] init];
  pigeonResult.query = query;
  return pigeonResult;
}
+ (FLTSearchRequest *)fromList:(NSArray *)list {
  FLTSearchRequest *pigeonResult = [[FLTSearchRequest alloc] init];
  pigeonResult.query = GetNullableObjectAtIndex(list, 0);
  NSAssert(pigeonResult.query != nil, @"");
  return pigeonResult;
}
+ (nullable FLTSearchRequest *)nullableFromList:(NSArray *)list {
  return (list) ? [FLTSearchRequest fromList:list] : nil;
}
- (NSArray *)toList {
  return @[
    (self.query ?: [NSNull null]),
  ];
}
@end

@implementation FLTSearchReply
+ (instancetype)makeWithResult:(NSString *)result {
  FLTSearchReply* pigeonResult = [[FLTSearchReply alloc] init];
  pigeonResult.result = result;
  return pigeonResult;
}
+ (FLTSearchReply *)fromList:(NSArray *)list {
  FLTSearchReply *pigeonResult = [[FLTSearchReply alloc] init];
  pigeonResult.result = GetNullableObjectAtIndex(list, 0);
  NSAssert(pigeonResult.result != nil, @"");
  return pigeonResult;
}
+ (nullable FLTSearchReply *)nullableFromList:(NSArray *)list {
  return (list) ? [FLTSearchReply fromList:list] : nil;
}
- (NSArray *)toList {
  return @[
    (self.result ?: [NSNull null]),
  ];
}
@end

@interface FLTFlutterCallNativeApiCodecReader : FlutterStandardReader
@end
@implementation FLTFlutterCallNativeApiCodecReader
- (nullable id)readValueOfType:(UInt8)type {
  switch (type) {
    case 128: 
      return [FLTSearchReply fromList:[self readValue]];
    case 129: 
      return [FLTSearchRequest fromList:[self readValue]];
    default:
      return [super readValueOfType:type];
  }
}
@end

@interface FLTFlutterCallNativeApiCodecWriter : FlutterStandardWriter
@end
@implementation FLTFlutterCallNativeApiCodecWriter
- (void)writeValue:(id)value {
  if ([value isKindOfClass:[FLTSearchReply class]]) {
    [self writeByte:128];
    [self writeValue:[value toList]];
  } else if ([value isKindOfClass:[FLTSearchRequest class]]) {
    [self writeByte:129];
    [self writeValue:[value toList]];
  } else {
    [super writeValue:value];
  }
}
@end

@interface FLTFlutterCallNativeApiCodecReaderWriter : FlutterStandardReaderWriter
@end
@implementation FLTFlutterCallNativeApiCodecReaderWriter
- (FlutterStandardWriter *)writerWithData:(NSMutableData *)data {
  return [[FLTFlutterCallNativeApiCodecWriter alloc] initWithData:data];
}
- (FlutterStandardReader *)readerWithData:(NSData *)data {
  return [[FLTFlutterCallNativeApiCodecReader alloc] initWithData:data];
}
@end

NSObject<FlutterMessageCodec> *FLTFlutterCallNativeApiGetCodec() {
  static FlutterStandardMessageCodec *sSharedObject = nil;
  static dispatch_once_t sPred = 0;
  dispatch_once(&sPred, ^{
    FLTFlutterCallNativeApiCodecReaderWriter *readerWriter = [[FLTFlutterCallNativeApiCodecReaderWriter alloc] init];
    sSharedObject = [FlutterStandardMessageCodec codecWithReaderWriter:readerWriter];
  });
  return sSharedObject;
}

void FLTFlutterCallNativeApiSetup(id<FlutterBinaryMessenger> binaryMessenger, NSObject<FLTFlutterCallNativeApi> *api) {
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.FlutterCallNativeApi.search"
        binaryMessenger:binaryMessenger
        codec:FLTFlutterCallNativeApiGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(searchRequest:error:)], @"FLTFlutterCallNativeApi api (%@) doesn't respond to @selector(searchRequest:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray *args = message;
        FLTSearchRequest *arg_request = GetNullableObjectAtIndex(args, 0);
        FlutterError *error;
        FLTSearchReply *output = [api searchRequest:arg_request error:&error];
        callback(wrapResult(output, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
}
@interface FLTNativeCallFlutterApiCodecReader : FlutterStandardReader
@end
@implementation FLTNativeCallFlutterApiCodecReader
- (nullable id)readValueOfType:(UInt8)type {
  switch (type) {
    case 128: 
      return [FLTSearchReply fromList:[self readValue]];
    case 129: 
      return [FLTSearchRequest fromList:[self readValue]];
    default:
      return [super readValueOfType:type];
  }
}
@end

@interface FLTNativeCallFlutterApiCodecWriter : FlutterStandardWriter
@end
@implementation FLTNativeCallFlutterApiCodecWriter
- (void)writeValue:(id)value {
  if ([value isKindOfClass:[FLTSearchReply class]]) {
    [self writeByte:128];
    [self writeValue:[value toList]];
  } else if ([value isKindOfClass:[FLTSearchRequest class]]) {
    [self writeByte:129];
    [self writeValue:[value toList]];
  } else {
    [super writeValue:value];
  }
}
@end

@interface FLTNativeCallFlutterApiCodecReaderWriter : FlutterStandardReaderWriter
@end
@implementation FLTNativeCallFlutterApiCodecReaderWriter
- (FlutterStandardWriter *)writerWithData:(NSMutableData *)data {
  return [[FLTNativeCallFlutterApiCodecWriter alloc] initWithData:data];
}
- (FlutterStandardReader *)readerWithData:(NSData *)data {
  return [[FLTNativeCallFlutterApiCodecReader alloc] initWithData:data];
}
@end

NSObject<FlutterMessageCodec> *FLTNativeCallFlutterApiGetCodec() {
  static FlutterStandardMessageCodec *sSharedObject = nil;
  static dispatch_once_t sPred = 0;
  dispatch_once(&sPred, ^{
    FLTNativeCallFlutterApiCodecReaderWriter *readerWriter = [[FLTNativeCallFlutterApiCodecReaderWriter alloc] init];
    sSharedObject = [FlutterStandardMessageCodec codecWithReaderWriter:readerWriter];
  });
  return sSharedObject;
}

@interface FLTNativeCallFlutterApi ()
@property(nonatomic, strong) NSObject<FlutterBinaryMessenger> *binaryMessenger;
@end

@implementation FLTNativeCallFlutterApi

- (instancetype)initWithBinaryMessenger:(NSObject<FlutterBinaryMessenger> *)binaryMessenger {
  self = [super init];
  if (self) {
    _binaryMessenger = binaryMessenger;
  }
  return self;
}
- (void)queryRequest:(FLTSearchRequest *)arg_request completion:(void (^)(FLTSearchReply *_Nullable, FlutterError *_Nullable))completion {
  FlutterBasicMessageChannel *channel =
    [FlutterBasicMessageChannel
      messageChannelWithName:@"dev.flutter.pigeon.NativeCallFlutterApi.query"
      binaryMessenger:self.binaryMessenger
      codec:FLTNativeCallFlutterApiGetCodec()];
  [channel sendMessage:@[arg_request ?: [NSNull null]] reply:^(id reply) {
    FLTSearchReply *output = reply;
    completion(output, nil);
  }];
}
@end

