// Autogenerated from Pigeon (v0.1.17), do not edit directly.
// See also: https://pub.dev/packages/pigeon
#import <Foundation/Foundation.h>
@protocol FlutterBinaryMessenger;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN

@class FLTSearchReply;
@class FLTSearchRequest;

@interface FLTSearchReply : NSObject
@property(nonatomic, copy, nullable) NSString * result;
@end

@interface FLTSearchRequest : NSObject
@property(nonatomic, copy, nullable) NSString * query;
@end

@protocol FLTFlutterCallNativeApi
-(nullable FLTSearchReply *)search:(FLTSearchRequest*)input error:(FlutterError *_Nullable *_Nonnull)error;
@end

extern void FLTFlutterCallNativeApiSetup(id<FlutterBinaryMessenger> binaryMessenger, id<FLTFlutterCallNativeApi> _Nullable api);

@interface FLTNativeCallFlutterApi : NSObject
- (instancetype)initWithBinaryMessenger:(id<FlutterBinaryMessenger>)binaryMessenger;
- (void)query:(FLTSearchRequest*)input completion:(void(^)(FLTSearchReply*, NSError* _Nullable))completion;
@end
NS_ASSUME_NONNULL_END
