// Autogenerated from Pigeon (v0.1.17), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import
// @dart = 2.8
import 'dart:async';
import 'dart:typed_data' show Uint8List, Int32List, Int64List, Float64List;

import 'package:flutter/services.dart';

class SearchReply {
  String result;

  // ignore: unused_element
  Object encode() {
    final Map<Object, Object> pigeonMap = <Object, Object>{};
    pigeonMap['result'] = result;
    return pigeonMap;
  }

  // ignore: unused_element
  static SearchReply decode(Object message) {
    final Map<Object, Object> pigeonMap = message as Map<Object, Object>;
    return SearchReply()
      ..result = pigeonMap['result'] as String;
  }
}

class SearchRequest {
  String query;

  // ignore: unused_element
  Object encode() {
    final Map<Object, Object> pigeonMap = <Object, Object>{};
    pigeonMap['query'] = query;
    return pigeonMap;
  }

  // ignore: unused_element
  static SearchRequest decode(Object message) {
    final Map<Object, Object> pigeonMap = message as Map<Object, Object>;
    return SearchRequest()
      ..query = pigeonMap['query'] as String;
  }
}

class FlutterCallNativeApi {
  Future<SearchReply> search(SearchRequest arg) async {
    final Object encoded = arg.encode();
    const BasicMessageChannel<Object> channel =
        BasicMessageChannel<Object>('dev.flutter.pigeon.FlutterCallNativeApi.search', StandardMessageCodec());
    final Map<Object, Object> replyMap = await channel.send(encoded) as Map<Object, Object>;
    if (replyMap == null) {
      throw PlatformException(
        code: 'channel-error',
        message: 'Unable to establish connection on channel.',
        details: null,
      );
    } else if (replyMap['error'] != null) {
      final Map<Object, Object> error = replyMap['error'] as Map<Object, Object>;
      throw PlatformException(
        code: error['code'] as String,
        message: error['message'] as String,
        details: error['details'],
      );
    } else {
      return SearchReply.decode(replyMap['result']);
    }
  }
}

abstract class NativeCallFlutterApi {
  SearchReply query(SearchRequest arg);
  static void setup(NativeCallFlutterApi api) {
    {
      const BasicMessageChannel<Object> channel =
          BasicMessageChannel<Object>('dev.flutter.pigeon.NativeCallFlutterApi.query', StandardMessageCodec());
      if (api == null) {
        channel.setMessageHandler(null);
      } else {
        channel.setMessageHandler((Object message) async {
          if (message == null) {
            return null;
          }
          final SearchRequest input = SearchRequest.decode(message);
          final SearchReply output = api.query(input);
          return output.encode();
        });
      }
    }
  }
}
